name: Run tests on self-hosted runners

on:
  push:
    branches: [ BigRefactor ]
  pull_request:
    branches: [ BigRefactor ]

jobs:
  test-windows:
    runs-on: [ self-hosted, Windows]
    name: Test on Windows

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      
      - name: Test
        run: go test -v ./...
        env:
          CGO_ENABLED: 0

  test-ubuntu:
    runs-on: [ self-hosted, Linux]
    name: Test on Ubuntu

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Test
        run: go test -v ./...
        env:
          CGO_ENABLED: 0